#!/bin/bash
# Clean current cache
cd buildscripts;
rm dist.zip*;
rm -rf deps prefix sdk;
# Symlink local SDK installation
mkdir sdk;
ln -s $ANDROID_HOME sdk/android-sdk-linux;
# Redownload all dependencies
sh download.sh;
# Compile all architectures
./buildall.sh --arch arm64 mpv;
./buildall.sh --arch x86_64 mpv;
./buildall.sh --arch armv7l mpv;
# Nothing bad ever happened.
exit 0;
