#!/bin/bash
# Clean current cache
git clean -xdf --exclude "*-entrypoint"

# Preparae dependencies build
cd buildscripts;
# Symlink local SDK installation
mkdir sdk;
ln -s $ANDROID_HOME sdk/android-sdk-linux;
# Redownload all dependencies
sh download.sh;

# Compile dependencies
./buildall.sh;
# Nothing bad ever happened.
exit 0;
