#!/bin/bash

cd mobile;

export PUB_CACHE=$(pwd)/.pub-cache
rm -rf $PUB_CACHE;
flutter clean;
git checkout pubspec.lock;

# Setup
sed -i -e "s/^\#f//" pubspec.yaml;
sed -i -e 's/^\/\/f //' android/app/build.gradle;

flutter config --no-analytics;
flutter pub get;
make translation;

cd $PUB_CACHE/hosted/pub.dev/geolocator_android-*/android;
sed -i -e '/gms/d' build.gradle;
cd src/main/java/com/baseflow/geolocator/location;
rm FusedLocationClient.java;
sed -i -e '/if (forceAndroidLocationManager) {/,/^  }/c return new LocationManagerClient(context,locationOptions);}' -e '/isGooglePlayServicesAvailable/,/^  }/d' -e '/gms/d' GeolocationManager.java;

cd ../../../../../../../../../../../../;
flutter build apk --release;

rm build/app/outputs/apk/release/app-release-unsigned.apk;
