#!/bin/bash

rm -rf node_modules;
source /usr/share/nvm/init-nvm.sh;
nvm install 22;
nvm use 22;
yarn add expo@52.0.42;
cp google-services.json.example google-services.json;
EXPO_NO_GIT_STATUS=1 npx --yes expo prebuild --platform android --clean;

# Set the date and time in seconds since epoch (January 1, 1970)
start_time=1640995200
# Get the current time in seconds since epoch
current_time=$(date +%s)
# Calculate the difference between the start time and the current time
diff=$(( $current_time - $start_time ))
# Convert the difference to minutes
minutes=$(( $diff / 60 ))
# Calculate the new versioncode
versioncode=$(( 2112312359 + $minutes ))
echo "Applying versionCode: ${versioncode}"
sed -i "s/        versionCode 1/        versionCode ${versioncode}/" android/app/build.gradle;
sed -i '/^            signingConfig signingConfigs\.debug$/d' android/app/build.gradle;
sed -i "s/applicationId 'xyz.blueskyweb.app'/applicationId 'xyz.blueskyweb.app'\n        ndk { abiFilters 'arm64-v8a' }/" android/app/build.gradle;

